name: CI
on: [push, pull_request]

env:
    OPENSSL_BRANCH: openssl-3.4.2
    USE_RPATH: yes
    PATCH_OPENSSL: 0
    GOST_PROVIDER_ENABLE_ONLINE_TESTS: 1

jobs:
    gcc-openssl-stable:
        runs-on: ubuntu-latest
        env:
            PATCH_OPENSSL: 1
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    clang-openssl-stable:
        runs-on: ubuntu-latest
        env:
            CC: clang
            PATCH_OPENSSL: 1
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    macos-openssl-stable:
        runs-on: macos-latest
        env:
            USE_RPATH:
            PATCH_OPENSSL: 1
            GOST_PROVIDER_ENABLE_ONLINE_TESTS: 0 # macOS runner has no network access to infotecs TLS1.3 server
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    gcc-openssl-master:
        runs-on: ubuntu-latest
        env:
            OPENSSL_BRANCH: master
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    macos-openssl-master:
        runs-on: macos-latest
        env:
            OPENSSL_BRANCH: master
            USE_RPATH:
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    gcc-asan-openssl-master:
        runs-on: ubuntu-latest
        env:
            OPENSSL_BRANCH: master
            ASAN: -DASAN=1
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    macos-asan-openssl-master:
        runs-on: macos-latest
        env:
            OPENSSL_BRANCH: master
            ASAN: -DASAN=1
            USE_RPATH:
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

    gcc-openssl-stable-x86:
        runs-on: ubuntu-latest
        env:
            CFLAGS: -m32
            LDFLAGS: -m32
            SETARCH: "setarch i386"
            APT_INSTALL: gcc-multilib
            PATCH_OPENSSL: 1
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: .github/before_script.sh
            - run: .github/script.sh

